// <auto-generated />
namespace Education_Solution.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbmodel3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbmodel3));
        
        string IMigrationMetadata.Id
        {
            get { return "201601131429064_dbmodel3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
